name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed for tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get previous version
      id: prev
      run: |
        VERSION=$(git describe --tags --abbrev=0 || echo "0.0.0")
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Bump version
      id: bump
      run: |
        VERSION=${{ steps.prev.outputs.version }}
        echo "Previous version: $VERSION"

        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)

        MSG=$(git log -1 --pretty=%B)
        if [[ "$MSG" == *"#major"* ]]; then
          MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
        elif [[ "$MSG" == *"#minor"* ]]; then
          MINOR=$((MINOR+1)); PATCH=0
        else
          PATCH=$((PATCH+1))
        fi

        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Create Git tag
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git tag ${{ steps.bump.outputs.new_version }}
        git push origin ${{ steps.bump.outputs.new_version }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t slimbentanfous1/healthcare-app:latest .

    - name: Push Docker image (latest)
      run: docker push slimbentanfous1/healthcare-app:latest

    - name: Push Docker image (versioned)
      run: |
        docker tag slimbentanfous1/healthcare-app:latest slimbentanfous1/healthcare-app:${{ steps.bump.outputs.new_version }}
        docker push slimbentanfous1/healthcare-app:${{ steps.bump.outputs.new_version }}
